<%-- 
    Document   : cd
    Created on : 1 Mar, 2017, 10:39:35 PM
    Author     : Udita Bose
--%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
</head>
<body bgcolor="white">
<h1 align="center"><font face="monotype corsiva" size="15"><b><u>Company Details</u></b></font></h1>
<h3 align="left"><font face="arial">1.)&nbsp;&nbsp;TCS</font></h3><img src="tcs.jpg" align="center" width="400"><br>Tata Consultancy Services Limited (TCS) is an Indian multinational information technology (IT) service, consulting and business solutions 1)company Headquartered in Mumbai, Maharashtra. It is a subsidiary of the <a href="Tata Group">Tata Group</a> and operates 
in 46 countries. TCS is one of the largest Indian companies by market capitalization ($80 billion).TCS is now placed among the ‘Big 4’ most valuable IT services brands worldwide.TCS alone generates 70% revenues of its parent company,<a href="Tata Sons.">Tata Sons.</a> In 2015, TCS is ranked 64th overall in the Forbes
World's Most Innovative Companies ranking, making it both the highest-ranked IT services company and the top Indian company.It is the world's 10th largest IT services provider by revenue. As of December 2015, it is ranked 10th on the Fortune India 500 list.On 12 January 2017,<a href="N.Chandrashekaran"> N.Chandrashekaran</a> 
was elevated as the chairman for Tata Sons.<a href="Rajesh Gopinathan"> Rajesh Gopinathan</a>was appointed as the new MD and CEO for TCS.<br>Official Website&nbsp;:&nbsp;&nbsp;<a href="http://www.tcs.com/">http://www.tcs.com/</a><br><br>

<h3 align="left"><font face="arial">2.)&nbsp;&nbsp;ACCENTURE</font></h3><img src="accenture.jpg" align="center" width="400"><br>Accenture PLC is a global professional services company which provides strategy, consulting, digital, technology and operations services. A Fortune Global 500 company,it has been incorporated in Dublin, Ireland, since 1 September 2009. In 2016, the company reported net revenues of $32.9 billion,with more than 394,000 employees serving clients in more than 200 cities in 120 countries. In 2015, the company had about 130,000 employees in India, about 48,000 in the US, and about 50,000 in the Philippines. Accenture's current clients include 94 of the Fortune Global 100 and more than three-quarters of the Fortune Global 500.
Accenture common equity is listed on the <a href="New York Stock Exchange">New York Stock Exchange</a>, under the symbol ACN, and was added to the S&P 500 index on 5 July 2011. In 2016, Fortune magazine named it as the world's most admired <a href="Information Technology Services">Information Technology Services</a> company.<br>Official Website&nbsp;:&nbsp;&nbsp;<a href="www.accenture.com">www.accenture.com</a><br><br>

<h3 align="left"><font face="arial">3.)&nbsp;&nbsp;ERICSSON</font></h3><img src="ericsson.png" align="center" width="400"><br>Ericsson (Telefonaktiebolaget L. M. Ericsson) is a multinational networking and telecommunications equipment and services company headquartered in Stockholm, Sweden. The company offers services, software and infrastructure in <a href="information and communications technology (ICT)">information and communications technology (ICT)</a> for telecommunications operators, traditional telecommunications and Internet Protocol (IP) networking equipment, mobile and fixed broadband, operations and business support services, cable television, IPTV, video systems, and an extensive services operation. Ericsson had 35% market share in the 2G/3G/4G mobile network infrastructure market in 2012.
The company was founded in 1876 by Lars Magnus Ericsson as of 2016 it is headquartered in Stockholm, Sweden. The company employs around 113,000 people and operates in around 180 countries.Ericsson holds over 39,000 granted patents as of May 2015, including many in wireless communications.<br>Official website&nbsp;:&nbsp;&nbsp;<a href="http://www.ericsson.com/">http://www.ericsson.com/</a><br><br>     

<h3 align="left"><font face="arial">4.)&nbsp;&nbsp;ORACLE</font></h3><img src="oracle.jpg" align="center" width="400"><br><a href="Oracle Corporation">Oracle Corporation</a> is an American multinational computer technology corporation, headquartered in Redwood Shores, California. The company primarily specializes in developing and marketing database software and technology, cloud engineered systems and enterprise software products—particularly its own brands of database management systems. In 2015 Oracle was the second-largest software maker by revenue, after Microsoft.
The company also develops and builds tools for database development and systems of middle-tier software, <a href="enterprise resource planning (ERP)">enterprise resource planning (ERP)</a> software, <a href="customer relationship management (CRM)">customer relationship management(CRM)</a> software and <a href="supply chain management (SCM)">supply chain management (SCM)</a> software.
<a href="Larry Ellison">Larry Ellison</a> co-founded Oracle Corporation in 1977 with <a href="Bob Miner">Bob Miner</a> and<a href="Ed Oates">Ed Oates</a> under the name <a href="Software development Laboratories (SDL)">Software Development Laboratories (SDL)</a>.<br>Official Website&nbsp;:&nbsp;&nbsp;<a href="http://www.oracle.com/">http://www.oracle.com/</a><br><br> 
<a href="https://www.igloosoftware.com/">https://www.igloosoftware.com/</a><br><br>

<h3 align="left"><font face="arial">5.)&nbsp;&nbsp;RADISYS</font></h3><img src="redisys.png" align="center" width="500"><br>Radisys Corporation is a publicly traded company located in Hillsboro, Oregon, United States that makes technology used by telecommunications companies in mobile networks. Founded in 1987 in Oregon by former employees of Intel, the company went public in 1995. The company's products are used in mobile network applications such as small cell radio access networks, wireless core network elements, deep packet inspection and policy management equipment; conferencing, and media services including voice, video and data. In 2015, Radisys first-quarter revenues totaled $48.7 million, and employed 700 people. <a href="Brian Bronson">Brian Bronson</a> is the company's chief executive officer.<br>Official Website&nbsp;:&nbsp;&nbsp;<a href="http://www.radisys.com/">http://www.radisys.com/</a><br><br>

<h3 align="left"><font face="arial">6.)&nbsp;&nbsp;HCL</font></h3><img src="hcl.jpg" align="center" width="400"><br>HCL Technologies Limited is an Indian multinational IT services company, headquartered in <a href="Noida">Noida</a>, Uttar Pradesh, India. It is a subsidiary of HCL Enterprise. Originally a <a href="research and development">research and development</a> division of HCL, it emerged as an independent company in 1991 when HCL ventured into the software services business. HCL Technologies (the abbreviation of Hindustan Computers Limited) offers services including <a href="IT consulting">IT consulting</a>, <a href="enterprise tranformation">enterprise transformation</a> , <a href="remote infrastructure management">remote infrastructure management</a> , engineering and <a href="R&D">R&D</a> , and <a href="business process outsourcing">business process outsourcing</a> (BPO).
The company has offices in 34 countries including the United States, European countries like France and Germany, and Northern Ireland in the United Kingdom. It operates across a number of sectors including aerospace and defense, automotive, consumer electronics, energy and utilities, financial services, government, industrial manufacturing, life sciences and healthcare, media and entertainment, mining and natural resources, public services, retail and consumer, semiconductor, server and storage, telecom, and travel, transportation, logistics, and hospitality.
HCL Technologies is on the <a href="Forbes Global 2000">Forbes Global 2000</a> list.It is among the top 20 largest publicly traded companies in India with a market capitalisation of $22.1 billion as of May 2015.As of August 2015, the company, along with its subsidiaries, had a consolidated revenue of $6.0 billion.
In the summer of 1976, a group of six engineers, all former employees of <a href="Delhi Cloth & General Mills">Delhi Cloth & General Mills</a>, led by <a href="Shiv Nadar">Shiv Nadar</a>, started a company that would make personal computers. Initially floated as Microcomp Limited, Nadar and his team started selling teledigital calculators to gather capital for their main product. On 11 August 1976, the company was renamed to HCL.<br>Official Website&nbsp;:&nbsp;&nbsp;<a href="http://hcltech.com/">http://hcltech.com/</a><br><br>

<h3 align="left"><font face="arial">7.)&nbsp;&nbsp;SABRE INDIA</font></h3><img src="sabre.jpg" align="center" width="400"><br>Sabre Corporation is a travel technology company based in Southlake, Texas. It is the largest Global Distribution Systems provider for air bookings in North America. American Airlines founded the company in 1960, and it was spun off in 2000. Texas Pacific Group and Silver Lake Partners acquired Sabre in 2007.Sabre began publicly trading on the NASDAQ in 2014.
Sabre Hospitality Solutions, an IT solutions provider, is the company's largest growing division
In 1953, C.R. Smith, the president of American Airlines, met Blair Smith, an IBM salesman, on a flight and developed the Sabre (the Semi-Automatic Business Research Environment) concept. The system was based on SAGE, the first major system to use interactive real-time computing IBM developed for military use. Sabre Corporation was founded in 1960 by American Airlines. Sabre Corporation installed the first Sabre reservation system in Briarcliff Manor, New York that year. The system consisted of two IBM 7090 mainframe computers and processed 84,000 calls per day.<br>Official Website&nbsp;:&nbsp;&nbsp;<a href="http://www.sabre.com/">http://www.sabre.com/</a><br><br>

<h3 align="left"><font face="arial">8.)&nbsp;&nbsp;TECH MAHINDRA</font></h3><br>Tech Mahindra Limited is an <a href="Indian multinational">Indian multinational</a> provider of <a href="information technology">information technology</a> (IT), networking technology solutions and <a href="Business Process Outsourcing">Business Process Outsourcing</a> (BPO) to the telecommunications industry. <a href="Anand Mahindra">Anand Mahindra</a> is the founder of Tech Mahindra, which is headquartered at <a href="Pune">Pune</a>, India.
Part of the <a href="Mahindra Group">Mahindra Group</a>, Tech Mahindra is a US$4.2 billion company with over 117,000 employees across 90 countries. It provides services to customers which include <a href="Fortune 500">Fortune 500</a> companies. It is also one of the Fab 50 companies in Asia, a list compiled by Forbes. Tech Mahindra was ranked #5 in India's software services (IT) firms and overall #111 in Fortune India 500 list for 2012.Tech Mahindra, on 25 June 2013, announced the completion of a merger with Mahindra Satyam.
Tech Mahindra has 825 active clients as of March 2016.<br>Official Website&nbsp;:&nbsp;&nbsp;<a href="http://www.techmahindra.com/">http://www.techmahindra.com/</a><br><br>

<h3 align="left"><font face="arial">9.)&nbsp;&nbsp;INFOSYS</font></h3><img src="info.jpg" align="center" width="400"><br>Infosys Limited (formerly Infosys Technologies Limited) is an Indian multinational corporation that provides business consulting, information technology and outsourcing services. It has the main headquarter in Bengaluru, India.
Infosys is the second-largest Indian IT services company by 2016 revenues, and the largest employer of H-1B visa professionals in the United States. On January 12, 2017, its market capitalisation was $34.38 Billion.
Co-founded in 1981 by 7 Engineers <a href="N. R. Narayana Murthy">N. R. Narayana Murthy</a>, Nandan Nilekani, N. S. Raghavan, S. Gopalakrishnan, S. D. Shibulal, K. Dinesh and Ashok Arora after they resigned from Patni Computer Systems. The company was incorporated as "Infosys Consultants Pvt Ltd." with a capital of ? 10,000 or US$250 (equivalent to about $659 in 2016) in Model Colony, Pune as the registered office. It signed its first client, Data Basics Corporation, in New York City. In 1983, the company's corporate headquarters was relocated from Pune to Bengaluru.<br>Official Website&nbsp;:&nbsp;&nbsp;<a href="http://www.infosys.com/">http://www.infosys.com//</a><br><br>

<h3 align="left"><font face="arial">10.)&nbsp;&nbsp;C-DAC</font></h3><img src="cdac1.jpg" align="center" width="400"><br>The Centre for Development of Advanced Computing (C-DAC) is a research and development organization under the Department of Electronics and Information Technology, Govt of India. The National Centre for Software Technology (NCST), ER&DCI and CEDTI were merged into C-DAC in 2003.
After being denied a Cray supercomputer by the United States in 1987 due to a fear of it being used for military purposes, India started a program to develop an indigenous supercomputer in collaboration with Russia. Supercomputers were considered a double edged weapon capable of assisting in the development of nuclear weapons.For the purpose of achieving self-sufficiency in the field, C-DAC was established by the Department of Electronics in 1988. Vijay Bhatkar was hired as the Director of C-DAC. The project was given an initial run of 3 years and an initial funding of ?30,00,00,000 as the same amount of money and time was usually expended to secure the purchase of a supercomputer from the US. In 1990, a prototype was produced and was benchmarked at the 1990 Zurich Supercomputering Show (CONPAR 1990?). It surpassed most other systems, placing second after US.
The final result of the effort was the PARAM 8000, which was installed in 1991. It is considered India's first supercomputer.<br>Official Website&nbsp;:&nbsp;&nbsp;<a href="http://www.cdac.in/">http://www.cdac.in/</a><br><br>
</body>
</html>
